name: Cache dependencies

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache dependencies
        id: cache-a9e6e73
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: cache-a9e6e73

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: prime-cache-a9e6e73
        run: |
          echo "Cache result: ${{ steps.cache-a9e6e73.outputs.cache-hit }}"
